### ISSUE TITLE
Hello, my name is Juraj Andrassy 

### ISSUE THREAD

**Issue by JAndrassy** [mrWheel/DSMRloggerAPI#2]
Hello, could you please correct my name in your documentation and blog.
if you want to refer someone from GitHub, check the name on the users page.
my name is Juraj Andrassy, not Jan Drassy

**Comment by mrWheel** [comment]
Ok, I'm so sorry, will do this
Can you tell me where you found the (wrong) references to your name?

- I changed it in one comment two times
- I changed it in github pages 1x

**Comment by JAndrassy** [comment]
thank you
I followed the links in TelnetStream repository's Insides Traffic
http://mrwheel.github.io/DSMRloggerWS/benodigdeBibliotheken/
http://mrwheel.github.io/DSMRloggerWS/installatieBibliotheken/
http://mrwheel.github.io/DSMRlogger2HTTP/installatieBibliotheken/
https://willem.aandewiel.nl/index.php/2018/08/28/slimme-meter-uitlezer/ 
https://opencircuit.nl/Blog/Aan-de-slag-met-de-ESP8266
https://opencircuit.be/Blog/Aan-de-slag-met-de-ESP8266
