### ISSUE TITLE
Zomer/wintertijd werkt niet goed

### ISSUE THREAD

**Issue by PhyxionNL** [mrWheel/DSMRloggerAPI#21]
In per Uur:
![image](https://user-images.githubusercontent.com/7643972/77854864-157e2d80-71ed-11ea-8a74-1052dbe03c3a.png)

**Comment by mrWheel** [comment]
@Phyxion 
Werkt prima (althans: er is mee te leven). Probleem is dat de klok een uur naar voren gaat waardoor de positie op "29[01:00-01:59]" niet "geraakt" wordt. In het RING bestand blijft hij dus op de waarde van 27[01:00-01:59] staan. Omdat de meterstanden daar lager zijn dan de positie ervoor geeft de GUI hier geen waarde (of waarde "0") waardoor de positie erná opeens heel groot wordt. 
Het loopt er na 24 uur uit.

**Comment by PhyxionNL** [comment]
Eigenlijk zou je de data op willen slaan aan de hand van DST en dan de UI erop aanpassen, dan kan je gewoon doortellen waar je gebleven bent. De telegrams geven ook een indicatie mee of er DST op zit of niet. Het is inderdaad niet een ramp dat het zo blijft, maar ik zat wel even te kijken waarom er ineens zo'n gigantisch verbruik was 😊

**Comment by mrWheel** [comment]
@Phyxion 
Ik heb het opgelost in de GUI
