### ISSUE TITLE
DSMRindex.js

### ISSUE THREAD

**Issue by debouttek** [mrWheel/DSMRloggerAPI#23]
Hi
I come from 1.2.1 and I did the update and have 1 question about the DSMRindex.js
1. backup of RING files OK
2. Upload ino.bin (BEversion) OK
3. Upload spiffs.bin OK
4. Put back the RING files OK
5. Then I downloaded the SOURCE CODE (ZIP) and extracted it and then did an upload of the file DSMRindex.js with FSexplorer  

Is step 5 good? Everything seems OK. 

Is there a way to backup the system/settings? Because the MQTT and cost settings are always gone when I do a update OTA?

**Comment by mrWheel** [comment]
@debouttek 

You did it all right. You could have just downloaded the `DSMRindex.js` file from github and upload that to SPIFFS, but this is OK! ... but .. if you flashed SPIFFS then the right files are all ready on your DSMR-logger and there is no need to upload the `DSMRindex.js` file by hand.

You can backup the system settings with the `FSexplorer` and [Download] the `DSMRsettings.ini` file to your computer just like you did with the RING files..
