### ISSUE TITLE
MQTT value/unit returned in JSON array 

### ISSUE THREAD

**Issue by wouterbouvy** [mrWheel/DSMRloggerAPI#28]
Hi @mrWheel,

First of all thanks for your great work on this. I'm really happy with my DSMR logger 4.5.
I was wondering on 2 things. 
1. Is there a specific reason why on MQTT the value and unit are returned in an array? We can expect only one value and unit for each topic, right?
2. Why is the topic name also returned in the MQTT message?

Example:
Topic: DSMR-API/power_delivered
"{"power_delivered": [{"value": 1.674, "unit": "kW"}}"]

Could be:
Topic: DSMR-API/power_delivered
{"value": 1.674, "unit": "kW"}}"

I made a code change to not add the [] in the jsonstuff.ino (to fix question 1). Do you want me to make a PR on this for future addition?

**Comment by mrWheel** [comment]
@wouterbouvy 

It was/is a design choice that has, in certain situations, a benefit in other situations not so.
But as I don’t want to break implementations for users who use this in there program’s or scripts I will not change it.
So, no pull-request please!
