### ISSUE TITLE
Trial with esp-12s module

### ISSUE THREAD

**Issue by tonysprenk** [mrWheel/DSMRloggerAPI#29]
Hi, 

Thanks for all the hard work on this very interesting repository! I would like to try the firmware before buying the official hardware. I have successfully installed DSMRloggerAPI on a generic esp-12s module. Unfortunately I haven’t been successful in collecting data from my slimme meter. I have connected gnd to gnd 3.3v to rts and rxd to txd. Does this firmware listen on a different gpio somehow? Is wat i want to achieve even possible? Thanks allot!

**Comment by mrWheel** [comment]
During setup the UART (Serial port) is swapped())
