### ISSUE TITLE
Wacht op eerste telegram BELGISCHE telegrammen Fluvius

### ISSUE THREAD

**Issue by debouttek** [mrWheel/DSMRloggerAPI#30]
Since 11/12/2020, the display of the logger shows: wait for the first telegram.
restart nothing helps.
is a Belgian digital meter.
any solution for this?

Op het display van de logger komt sinds 11/12/2020 te staan : wacht op eerste telegram. 
herstart helpt niets. 
is een Belgische digitale meter. 
enige oplossing hiervoor?

**Comment by debouttek** [comment]
Nobody can help?
Hardware is the print I bought on opencircuit.be. Smart meter reader V4-5 Assembled.
I have already fully reloaded the firmware.
I have already closed and reopened the gate via the fluvius website.

Reading from api: ipaddress / api / v1 / dev / time gives the following result.
{"devtime": [
{"name": "timestamp", "value": "010101010101X"},
{"name": "time", "value": "2001-01-01 01:01:01"},
{"name": "epoch", "value": 978311136}
]}

Read from api: ipadres/api/v1/dev/info gives the following result.
{"devinfo": [
{"name": "author", "value": "Willem Aandewiel (www.aandewiel.nl)"},
{"name": "fwversion", "value": "v2.0.1 (04/17/2020)"},
{"name": "compiled", "value": "Dec 26 2020 12:59:06"},
{"name": "hostname", "value": "DSMR API"},
{"name": "ipaddress", "value": "192.168.0.x"}, (IP address changed by myself for this message)
{"name": "macaddress", "value": "xx: xx: xx: xx: xx: xx"}, (xx adjusted by myself for this message)
{"name": "indexfile", "value": "DSMRindex.html"},
{"name": "freeheap", "value": 18112, "unit": "bytes"},
{"name": "maxfreeblock", "value": 17352, "unit": "bytes"},
{"name": "chipid", "value": "c2fd3f"},
{"name": "coreversion", "value": "2_7_4"},
{"name": "sdkversion", "value": "2.2.1 (cfd48f3)"},
{"name": "cpufreq", "value": 80, "unit": "MHz"},
{"name": "sketchsize", "value": 504.766, "unit": "kB"},
{"name": "freesketchspace", "value": 1540.000, "unit": "kB"},
{"name": "flashchipid", "value": "001640EF"},
{"name": "flashchipsize", "value": 4,000, "unit": "MB"},
{"name": "flashchiprealsize", "value": 4,000, "unit": "MB"},
{"name": "spiffssize", "value": 2,000, "unit": "MB"},
{"name": "flashchipspeed", "value": 80,000, "unit": "MHz"},
{"name": "flashchipmode", "value": "DOUT"},
{"name": "boardtype", "value": "ESP8266_GENERIC"},
{"name": "compileoptions", "value": "[USE_REQUEST_PIN] [USE_BELGIUM_PROTOCOL] [USE_UPDATE_SERVER] [USE_MQTT]"},
{"name": "ssid", "value": "my network"},
{"name": "wifirssi", "value": -78},
{"name": "uptime", "value": "0 (d) -00: 11 (H: m)"},
{"name": "oled_type", "value": 1},
{"name": "oled_flip_screen", "value": 0},
{"name": "smhasaseinfo", "value": 1},
{"name": "telegraminterval", "value": 10},
{"name": "telegramcount", "value": 66},
{"name": "telegramerrors", "value": 66},
{"name": "mqttbroker", "value": "192.168.0.x: 1883"},
{"name": "mqttinterval", "value": 10},
{"name": "mqttbroker_connected", "value": "yes"},
{"name": "reboots", "value": 6},
{"name": "lastreset", "value": "External System"}
]}

Someone who can / wants to view this?
Niemand die kan helpen?
Hardware is de print die ik kocht op opencircuit.be. Slimme meter uitlezer V4-5 Geassembleerd.
Ik heb reeds de firmware volledig opnieuw opgeladen.
Ik heb reeds de poort gesloten en weer geopend via de website van fluvius.

Uitlezen van api: ipadres/api/v1/dev/time geeft volgend resultaat.
{"devtime":[
{"name": "timestamp", "value": "010101010101X"},
{"name": "time", "value": "2001-01-01 01:01:01"},
{"name": "epoch", "value": 978311136}
]}

Uitlezen van api: ipadres/api/v1/dev/info geeft volgend resultaat.
{"devinfo":[
{"name": "author", "value": "Willem Aandewiel (www.aandewiel.nl)"},
{"name": "fwversion", "value": "v2.0.1 (17-04-2020)"},
{"name": "compiled", "value": "Dec 26 2020 12:59:06"},
{"name": "hostname", "value": "DSMR-API"},
{"name": "ipaddress", "value": "192.168.0.x"}, (IPadres door mezelf aangepast voor deze melding)
{"name": "macaddress", "value": "xx:xx:xx:xx:xx:xx"},  (xx door mezelf aangepast voor deze melding)
{"name": "indexfile", "value": "DSMRindex.html"},
{"name": "freeheap", "value": 18112, "unit": "bytes"},
{"name": "maxfreeblock", "value": 17352, "unit": "bytes"},
{"name": "chipid", "value": "c2fd3f"},
{"name": "coreversion", "value": "2_7_4"},
{"name": "sdkversion", "value": "2.2.1(cfd48f3)"},
{"name": "cpufreq", "value": 80, "unit": "MHz"},
{"name": "sketchsize", "value": 504.766, "unit": "kB"},
{"name": "freesketchspace", "value": 1540.000, "unit": "kB"},
{"name": "flashchipid", "value": "001640EF"},
{"name": "flashchipsize", "value": 4.000, "unit": "MB"},
{"name": "flashchiprealsize", "value": 4.000, "unit": "MB"},
{"name": "spiffssize", "value": 2.000, "unit": "MB"},
{"name": "flashchipspeed", "value": 80.000, "unit": "MHz"},
{"name": "flashchipmode", "value": "DOUT"},
{"name": "boardtype", "value": "ESP8266_GENERIC"},
{"name": "compileoptions", "value": "[USE_REQUEST_PIN][USE_BELGIUM_PROTOCOL][USE_UPDATE_SERVER][USE_MQTT]"},
{"name": "ssid", "value": "mijn netwerk"},
{"name": "wifirssi", "value": -78},
{"name": "uptime", "value": "0(d)-00:11(H:m)"},
{"name": "oled_type", "value": 1},
{"name": "oled_flip_screen", "value": 0},
{"name": "smhasfaseinfo", "value": 1},
{"name": "telegraminterval", "value": 10},
{"name": "telegramcount", "value": 66},
{"name": "telegramerrors", "value": 66},
{"name": "mqttbroker", "value": "192.168.0.x:1883"},
{"name": "mqttinterval", "value": 10},
{"name": "mqttbroker_connected", "value": "yes"},
{"name": "reboots", "value": 6},
{"name": "lastreset", "value": "External System"}
]}

Iemand die dit eens kan/wil bekijken?

**Comment by Tokn59** [comment]
Zeker dat die P1 poort openstaat? Dat kan wel even duren en je krijgt normaal gezien ook een verzoek tot autorisatie ....

Sent from my iPhone

On 28 Dec 2020, at 19:58, debouttek <notifications@github.com> wrote:

﻿

Nobody can help?
Hardware is the print I bought on opencircuit.be. Smart meter reader V4-5 Assembled.
I have already fully reloaded the firmware.
I have already closed and reopened the gate via the fluvius website.

Reading from api: ipaddress / api / v1 / dev / time gives the following result.
{"devtime": [
{"name": "timestamp", "value": "010101010101X"},
{"name": "time", "value": "2001-01-01 01:01:01"},
{"name": "epoch", "value": 978311136}
]}

Read from api: ipadres/api/v1/dev/info gives the following result.
{"devinfo": [
{"name": "author", "value": "Willem Aandewiel (www.aandewiel.nl)"},
{"name": "fwversion", "value": "v2.0.1 (04/17/2020)"},
{"name": "compiled", "value": "Dec 26 2020 12:59:06"},
{"name": "hostname", "value": "DSMR API"},
{"name": "ipaddress", "value": "192.168.0.x"}, (IP address changed by myself for this message)
{"name": "macaddress", "value": "xx: xx: xx: xx: xx: xx"}, (xx adjusted by myself for this message)
{"name": "indexfile", "value": "DSMRindex.html"},
{"name": "freeheap", "value": 18112, "unit": "bytes"},
{"name": "maxfreeblock", "value": 17352, "unit": "bytes"},
{"name": "chipid", "value": "c2fd3f"},
{"name": "coreversion", "value": "2_7_4"},
{"name": "sdkversion", "value": "2.2.1 (cfd48f3)"},
{"name": "cpufreq", "value": 80, "unit": "MHz"},
{"name": "sketchsize", "value": 504.766, "unit": "kB"},
{"name": "freesketchspace", "value": 1540.000, "unit": "kB"},
{"name": "flashchipid", "value": "001640EF"},
{"name": "flashchipsize", "value": 4,000, "unit": "MB"},
{"name": "flashchiprealsize", "value": 4,000, "unit": "MB"},
{"name": "spiffssize", "value": 2,000, "unit": "MB"},
{"name": "flashchipspeed", "value": 80,000, "unit": "MHz"},
{"name": "flashchipmode", "value": "DOUT"},
{"name": "boardtype", "value": "ESP8266_GENERIC"},
{"name": "compileoptions", "value": "[USE_REQUEST_PIN] [USE_BELGIUM_PROTOCOL] [USE_UPDATE_SERVER] [USE_MQTT]"},
{"name": "ssid", "value": "my network"},
{"name": "wifirssi", "value": -78},
{"name": "uptime", "value": "0 (d) -00: 11 (H: m)"},
{"name": "oled_type", "value": 1},
{"name": "oled_flip_screen", "value": 0},
{"name": "smhasaseinfo", "value": 1},
{"name": "telegraminterval", "value": 10},
{"name": "telegramcount", "value": 66},
{"name": "telegramerrors", "value": 66},
{"name": "mqttbroker", "value": "192.168.0.x: 1883"},
{"name": "mqttinterval", "value": 10},
{"name": "mqttbroker_connected", "value": "yes"},
{"name": "reboots", "value": 6},
{"name": "lastreset", "value": "External System"}
]}

Someone who can / wants to view this?
Niemand die kan helpen?
Hardware is de print die ik kocht op opencircuit.be. Slimme meter uitlezer V4-5 Geassembleerd.
Ik heb reeds de firmware volledig opnieuw opgeladen.
Ik heb reeds de poort gesloten en weer geopend via de website van fluvius.

Uitlezen van api: ipadres/api/v1/dev/time geeft volgend resultaat.
{"devtime":[
{"name": "timestamp", "value": "010101010101X"},
{"name": "time", "value": "2001-01-01 01:01:01"},
{"name": "epoch", "value": 978311136}
]}

Uitlezen van api: ipadres/api/v1/dev/info geeft volgend resultaat.
{"devinfo":[
{"name": "author", "value": "Willem Aandewiel (www.aandewiel.nl)"},
{"name": "fwversion", "value": "v2.0.1 (17-04-2020)"},
{"name": "compiled", "value": "Dec 26 2020 12:59:06"},
{"name": "hostname", "value": "DSMR-API"},
{"name": "ipaddress", "value": "192.168.0.x"}, (IPadres door mezelf aangepast voor deze melding)
{"name": "macaddress", "value": "xx:xx:xx:xx:xx:xx"}, (xx door mezelf aangepast voor deze melding)
{"name": "indexfile", "value": "DSMRindex.html"},
{"name": "freeheap", "value": 18112, "unit": "bytes"},
{"name": "maxfreeblock", "value": 17352, "unit": "bytes"},
{"name": "chipid", "value": "c2fd3f"},
{"name": "coreversion", "value": "2_7_4"},
{"name": "sdkversion", "value": "2.2.1(cfd48f3)"},
{"name": "cpufreq", "value": 80, "unit": "MHz"},
{"name": "sketchsize", "value": 504.766, "unit": "kB"},
{"name": "freesketchspace", "value": 1540.000, "unit": "kB"},
{"name": "flashchipid", "value": "001640EF"},
{"name": "flashchipsize", "value": 4.000, "unit": "MB"},
{"name": "flashchiprealsize", "value": 4.000, "unit": "MB"},
{"name": "spiffssize", "value": 2.000, "unit": "MB"},
{"name": "flashchipspeed", "value": 80.000, "unit": "MHz"},
{"name": "flashchipmode", "value": "DOUT"},
{"name": "boardtype", "value": "ESP8266_GENERIC"},
{"name": "compileoptions", "value": "[USE_REQUEST_PIN][USE_BELGIUM_PROTOCOL][USE_UPDATE_SERVER][USE_MQTT]"},
{"name": "ssid", "value": "mijn netwerk"},
{"name": "wifirssi", "value": -78},
{"name": "uptime", "value": "0(d)-00:11(H:m)"},
{"name": "oled_type", "value": 1},
{"name": "oled_flip_screen", "value": 0},
{"name": "smhasfaseinfo", "value": 1},
{"name": "telegraminterval", "value": 10},
{"name": "telegramcount", "value": 66},
{"name": "telegramerrors", "value": 66},
{"name": "mqttbroker", "value": "192.168.0.x:1883"},
{"name": "mqttinterval", "value": 10},
{"name": "mqttbroker_connected", "value": "yes"},
{"name": "reboots", "value": 6},
{"name": "lastreset", "value": "External System"}
]}

Iemand die dit eens kan/wil bekijken?

**Comment by debouttek** [comment]
> Zeker dat die P1 poort openstaat? Dat kan wel even duren en je krijgt normaal gezien ook een verzoek tot autorisatie ....
> […](#)

De poort staat zeker open. Als ik ze sluit dan valt de spanning van het bordje weg en is deze dus uit. Als ik de poort weer open dan start het bordje weer mooi op.

**Comment by Tokn59** [comment]
Ik kijk morgen even naar je instellingen !

Sent from my iPad

On 28 Dec 2020, at 21:10, debouttek <notifications@github.com> wrote:

﻿

Zeker dat die P1 poort openstaat? Dat kan wel even duren en je krijgt normaal gezien ook een verzoek tot autorisatie ....
…

De poort staat zeker open. Als ik ze sluit dan valt de spanning van het bordje weg en is deze dus uit. Als ik de poort weer open dan start het bordje weer mooi op.

**Comment by debouttek** [comment]
@Tokn59 
had je nog de tijd gevonden om eens te kijken naar de instellingen?

Als ik in het dashboard naar ALL FIELDS klik dan is dit leeg.

Doe ik dit via IPADRES/api/v1/sm/fields ingeef krijg ik hetvolgende:

{"fields":[
{"name": "identification", "value": "FLU5\25xxxxx_A"}, (door mezelf aangepast)
{"name": "p1_version", "value": "50214"},
{"name": "timestamp", "value": "210103120933W"},
{"name": "equipment_id", "value": "xxxxxxxxxxxx"}, (door mezelf aangepast)
{"name": "energy_delivered_tariff1", "value": 1998.546, "unit": "kWh"},
{"name": "energy_delivered_tariff2", "value": 1754.648, "unit": "kWh"},
{"name": "energy_returned_tariff1", "value": 2638.063, "unit": "kWh"},
{"name": "energy_returned_tariff2", "value": 900.363, "unit": "kWh"},
{"name": "electricity_tariff", "value": "0002"},
{"name": "power_delivered", "value": 1.417, "unit": "kW"},
{"name": "power_returned", "value": 0.000, "unit": "kW"},
{"name": "electricity_threshold", "value": "-"},
{"name": "electricity_switch_position", "value": "-"},
{"name": "electricity_failures", "value": "-"},
{"name": "electricity_long_failures", "value": "-"},
{"name": "electricity_failure_log", "value": "-"},
{"name": "electricity_sags_l1", "value": "-"},
{"name": "electricity_sags_l2", "value": "-"},
{"name": "electricity_sags_l3", "value": "-"},
{"name": "electricity_swells_l1", "value": "-"},
{"name": "electricity_swells_l2", "value": "-"},
{"name": "electricity_swells_l3", "value": "-"},
{"name": "message_short", "value": "-"},
{"name": "message_long", "value": "-"},
{"name": "voltage_l1", "value": 233.100, "unit": "V"},
{"name": "voltage_l2", "value": "-"},
{"name": "voltage_l3", "value": "-"},
{"name": "current_l1", "value": 0, "unit": "A"},
{"name": "current_l2", "value": "-"},
{"name": "current_l3", "value": "-"},
{"name": "power_delivered_l1", "value": "-"},
{"name": "power_delivered_l2", "value": "-"},
{"name": "power_delivered_l3", "value": "-"},
{"name": "power_returned_l1", "value": "-"},
{"name": "power_returned_l2", "value": "-"},
{"name": "power_returned_l3", "value": "-"},
{"name": "gas_device_type", "value": "-"},
{"name": "gas_equipment_id", "value": "-"},
{"name": "gas_valve_position", "value": "-"},
{"name": "gas_delivered", "value": "-"},
{"name": "thermal_device_type", "value": "-"},
{"name": "thermal_equipment_id", "value": "-"},
{"name": "thermal_valve_position", "value": "-"},
{"name": "thermal_delivered", "value": "-"},
{"name": "water_device_type", "value": "-"},
{"name": "water_equipment_id", "value": "-"},
{"name": "water_valve_position", "value": "-"},
{"name": "water_delivered", "value": "-"},
{"name": "slave_device_type", "value": "-"},
{"name": "slave_equipment_id", "value": "-"},
{"name": "slave_valve_position", "value": "-"},
{"name": "slave_delivered", "value": "-"}
]}

**Comment by Tokn59** [comment]
Voor zover ik kan zien is aan je DSMR kant alles OK. Je zou voor alle zekerheid nog eens kunnen herflashen (ERASE ALL) en meteen ook de wijzigingen doorvoeren van de laatste firmware van de Fluvius meter. Daartoe dien je in de DSMR-BE folder de file fields-be.h aan te passen als volgt :

/* Adaptation for new Fluvius Firmware BE meters by T.K> */
/* DEFINE_FIELD(current_l1, uint16_t, ObisId(1, 0, 31, 7, 0), IntField, units::A); */
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A, units::mA);//
/* Instantaneous current L2 in A resolution */
//DEFINE_FIELD(current_l2, uint16_t, ObisId(1, 0, 51, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::mA);
/* Instantaneous current L3 in A resolution */
//DEFINE_FIELD(current_l3, uint16_t, ObisId(1, 0, 71, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::mA);
/* Instantaneous active power L1 (+P) in W resolution */

Dan hercompileren en flashen. Als dat niets oplevert zou ik toch even contact opnemen met de support van Fluvius.

**Comment by debouttek** [comment]
@Tokn59 
Bedankt. Waar haal je deze info?
Bij het compileren krijg ik nog een foutmelding na het aanpassen van fields-be.h

exit status 1
'current_l2' was not declared in this scope

**Comment by Tokn59** [comment]
My mistake .. use thits correction :

/* Adaptation for new Fluvius Firmware BE meters by T.K> */
/* DEFINE_FIELD(current_l1, uint16_t, ObisId(1, 0, 31, 7, 0), IntField, units::A); */
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A, units::mA);//
/* Instantaneous current L2 in A resolution */
//DEFINE_FIELD(current_l2, uint16_t, ObisId(1, 0, 51, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l2, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::mA);
/* Instantaneous current L3 in A resolution */
//DEFINE_FIELD(current_l3, uint16_t, ObisId(1, 0, 71, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l3, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::mA);

**Comment by debouttek** [comment]
YES!! Thanks. It works now.

Waar haalde je de info van Fluvius? Dan kan ik in de toekomst daar ook gaan zoeken.

**Comment by debouttek** [comment]
Waar kan ik dit doorgeven zodat dit in een nieuwe versie kan bijgezet worden?

**Comment by Tokn59** [comment]
Fluvius Smart Meter Documentatie, formaat en definitie telegram .... Juiste link moet ik eens opzoeken ...

**Comment by Tokn59** [comment]
Voor de Belgische gebruikers die de nieuwe Fluvius firmware (ongevraagd) hebben ontvangen, volgende lijnen moeten gewijzigd worden in fields-be.h 

/* Adaptation for new Fluvius Firmware BE meters by T.K> */
/* DEFINE_FIELD(current_l1, uint16_t, ObisId(1, 0, 31, 7, 0), IntField, units::A); */
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A, units::mA);//
/* Instantaneous current L2 in A resolution */
//DEFINE_FIELD(current_l2, uint16_t, ObisId(1, 0, 51, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l2, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::mA);
/* Instantaneous current L3 in A resolution */
//DEFINE_FIELD(current_l3, uint16_t, ObisId(1, 0, 71, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l3, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::mA);

Vergeet niet opnieuw te compileren met de optie :

#define USE_BELGIUM_PROTOCOL      // define if Slimme Meter is a Belgium Smart Meter

Op deze manier krijg je de juiste "current" informatie van de telegrammen.

**Comment by wijnanb** [comment]
Created a PR for this https://github.com/mrWheel/arduino-dsmr-be/pull/4
