### ISSUE TITLE
time fixed at value in the past

### ISSUE THREAD

**Issue by RKS7204** [mrWheel/DSMRloggerAPI#31]
![DSMR3](https://user-images.githubusercontent.com/58250194/104848155-fa97b980-58e3-11eb-991c-370386aa7b4f.png)
![DSMR2](https://user-images.githubusercontent.com/58250194/104848156-fb305000-58e3-11eb-90c4-a8de23e9e671.png)
![DSMR1](https://user-images.githubusercontent.com/58250194/104848157-fb305000-58e3-11eb-87e2-58b6e88bc2d2.png)

The time is fixed at 2021-01-11 19:52.
I updated firmware and spiffs.
After that time is fixed at 2001-01-01 01:01:01
Because time is not right, all measurements are placed in wrong interval.

Is it possible to adjust time by timestamp from telegram?
Or maybe a setting to fill in the time server?

**Comment by RKS7204** [comment]
I tried to recompile the project with this adjustments as mentioned here.

/* Adaptation for new Fluvius Firmware BE meters by T.K> /
/ DEFINE_FIELD(current_l1, uint16_t, ObisId(1, 0, 31, 7, 0), IntField, units::A); /
DEFINE_FIELD(current_l1, FixedValue, ObisId(1, 0, 31, 7, 0), FixedField, units::A, units::mA);//
/ Instantaneous current L2 in A resolution /
//DEFINE_FIELD(current_l2, uint16_t, ObisId(1, 0, 51, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l2, FixedValue, ObisId(1, 0, 51, 7, 0), FixedField, units::A, units::mA);
/ Instantaneous current L3 in A resolution */
//DEFINE_FIELD(current_l3, uint16_t, ObisId(1, 0, 71, 7, 0), IntField, units::A);
DEFINE_FIELD(current_l3, FixedValue, ObisId(1, 0, 71, 7, 0), FixedField, units::A, units::mA);

But I get this error : 

D:\Documenten\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:413: undefined reference to `dsmr::fields::identification::id'

Can someone give me some help?

THX

**Comment by Tokn59** [comment]
It probably refers to ESP8266WebServer.h which is part of the ESP8266 Core. Can you update all your libraries to the latest version and try again ?

**Comment by RKS7204** [comment]
Same result. I'm using version 2.7.4.

I attached the complete log file.

[Error.txt](https://github.com/mrWheel/DSMRloggerAPI/files/5828754/Error.txt)

**Comment by RKS7204** [comment]
Kan er iemand de gecompileerde gewijzigde Belgische bin bezorgen aan me?
Ik krijg dit echt niet gecompileerd.

**Comment by Tokn59** [comment]
Hoe kan ik je dat best bezorgen ?

**Comment by RKS7204** [comment]
Een link via google drive of iets dergelijks?

**Comment by Tokn59** [comment]
https://we.tl/t-8vje9XRIdW

**Comment by RKS7204** [comment]
Thank you
