### ISSUE TITLE
Compiler arduino stops with error @line  398  restapi

### ISSUE THREAD

**Issue by PetersPlace** [mrWheel/DSMRloggerAPI#34]
Compiler arduino stops with error @line  398  restapi
with:
 **exit status 1
expected primary-expression before ')' token**

How do resolf this error, i'am not diehard programmer in arduino

**Comment by hoekbrwr** [comment]
Choose the board "Generic ESP8266 module" and the fault will magically disappear!

**Comment by mrWheel** [comment]
As @hoekbrwr say's
