### ISSUE TITLE
Belgian DSMR parse error

### ISSUE THREAD

**Issue by DjesLoc** [mrWheel/DSMRloggerAPI#35]
Via Telnet:
processSlimm( 166): Parse error
1-0:31.7.0(000.91*A)
                      ^
Missing unit

raw telegram:
1-0:1.8.1(000861.264*kWh)
1-0:1.8.2(001283.641*kWh)
1-0:2.8.1(000054.676*kWh)
1-0:2.8.2(000026.493*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.000*kW)
1-0:2.7.0(00.621*kW)
1-0:21.7.0(00.000*kW)
1-0:41.7.0(00.000*kW)
1-0:61.7.0(00.000*kW)
1-0:22.7.0(00.077*kW)
1-0:42.7.0(00.219*kW)
1-0:62.7.0(00.325*kW)
1-0:32.7.0(233.1*V)
1-0:52.7.0(232.4*V)
1-0:72.7.0(233.3*V)
1-0:31.7.0(000.94*A)
1-0:51.7.0(001.38*A)
1-0:71.7.0(001.43*A)

**Comment by mrWheel** [comment]
Is this still an issue?

**Comment by mrWheel** [comment]
Solved in v3
