### ISSUE TITLE
How to adjust clock

### ISSUE THREAD

**Issue by MathieuMH** [mrWheel/DSMRloggerAPI#36]
Hi,

Today I noticed that the time is off on my DSMR logger. It is showing 2020-12-10 16:59:55 which is incorrect. 
I'm unable to find a way to adjust it.
Please guide me!

Kind regards,
Mathieu

**Comment by Tokn59** [comment]
That's weird ... I believe the timestamp comes from the telegrams. Are you receiving telegrams ?

**Comment by MathieuMH** [comment]
Yes, I get actual (correct values). A telegram I captured just now as an example:
`0-0:96.1.4(50215)
0-0:96.1.1(3153414731313030303633313635)
0-0:1.0.0(210309215610W)
1-0:1.8.1(001422.970*kWh)
1-0:1.8.2(001724.786*kWh)
1-0:2.8.1(002034.167*kWh)
1-0:2.8.2(000759.596*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.498*kW)
1-0:2.7.0(00.000*kW)
1-0:21.7.0(00.498*kW)
1-0:22.7.0(00.000*kW)
1-0:32.7.0(233.1*V)
1-0:31.7.0(002.96*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
0-1:24.1.0(003)
0-1:96.1.1(37464C4F32313139303930323337)
0-1:24.4.0(1)
0-1:24.2.3(210309215505W)(01554.860*m3)`

**Comment by mrWheel** [comment]
Have you compiled with NTP support?
That should only be used with DSMR pré 40 (that has no timestamp record in the telegram).
