### ISSUE TITLE
Feature request: HJMindex with support for negative (returned) energy

### ISSUE THREAD

**Issue by ProBackup-nl** [mrWheel/DSMRloggerAPI#37]
Having solar panels that return energy (no delivery during sunny times) makes HJMindex display "0.000" for all phases.

It would be great if the gauges can go negative.

Trying to fix that myself, I think when delivery is 0, then fetch returned energy. Though `nvKW<0` inside the `if (nvKW == 0 )` block, and becomes 0 just after it: `console.log("nvKW = "+ nvKW.toString())`.
 
I am stuck, possibly due to asynchronous requests. Any help is welcome.

```
function update()
{
    var phase;
    for( let phase = 1 ; phase <= PHASES ; phase++ )
    {
        fetch(APIGW+"v1/sm/fields/power_delivered_l"+phase)
        .then(response => response.json())
        .then(json => 
          {
            for( let j in json.fields ){
                // console.log(json.fields[j].name+" -- "+ "power_delivered_l"+i.toString())
                if (json.fields[j].name.startsWith("power_delivered_l"))
                {

                    myPhase = Number(json.fields[j].name.replace('power_delivered_l',''));

                    let cvKW=document.getElementById(json.fields[j].name).innerHTML
                    let nvKW=Number(json.fields[j].value)
                    if (nvKW == 0 ) // check if power is generated
                    {
                        //console.log("nvKW = "+nvKW.toString())
                        fetch(APIGW+"v1/sm/fields/power_returned_l"+myPhase)
                        .then(response => response.json())
                        .then(json2 => 
                          {
                            for( let jr in json2.fields ){
                                if (json2.fields[jr].name.startsWith("power_returned_l"))
                                {
                                    let nvKW=-1*Number(json2.fields[jr].value)
                                    console.log(json2.fields[jr].name+" = "+ nvKW.toString())
                                    ˆˆˆˆ<- here nvKW < 0
                                }
                            }
                          }
                        );
                    }

                    console.log("nvKW = "+ nvKW.toString())
                                    ˆˆˆˆ<- here nvKW = 0
                    let nvA=nvKW*1000.0/220.0  // estimated amps using fixed voltage
```

**Comment by ProBackup-nl** [comment]
Patch in #38 will result in such a display when energy is returned to grid
![kW trend negative](https://user-images.githubusercontent.com/515451/115878110-74da5b80-a448-11eb-9707-5c199befc4a8.jpg)
:

**Comment by ProBackup-nl** [comment]
PR #39 adds support for single phase meters, updating only the "Total" column. Though not tested due to no access to a single phase meter. Error handling added. Minor visual improvements to not trend colour the first measurement and have a fixed number of decimals for the Amps value.

ToDo: detect new (p1_version >= 50) and decrease update interval from 10 seconds to 1 second.

![kW trend-4](https://user-images.githubusercontent.com/515451/115973824-303de580-a558-11eb-8e7c-390e441a5104.jpg)

**Comment by mrWheel** [comment]
Done (by yourself?)!

**Comment by ProBackup-nl** [comment]
Yes I did this indeed. Note PR #39 is still open.
