### ISSUE TITLE
NTP sync is not working

### ISSUE THREAD

**Issue by gvdhoven** [mrWheel/DSMRloggerAPI#46]
Enabled 
```
#define USE_NTP_TIME 
```

And see in serial monitor:
```
[20:58:28][  20008| 19824] setup       ( 368): Time is set to [210605205828W] from NTP
```

(The "W" is strange btw) and no time is set if i debug the `/api/v1/dev/time` request:
![image](https://user-images.githubusercontent.com/186093/120904037-296fbb80-c64a-11eb-8c44-d0f7c72d9207.png)

Also reflects as such in the UI:
![image](https://user-images.githubusercontent.com/186093/120904054-43a99980-c64a-11eb-9f54-1dd627d80f35.png)

**Comment by mrWheel** [comment]
NTP time is only used with the pré40 DSMR protocol (2.2 - 3.0).
Otherwise the time is taken from the Slimme Meter "timestamp" field.
