### ISSUE TITLE
3.0.1 for ESP-01 

### ISSUE THREAD

**Issue by JordVisbeen** [mrWheel/DSMRloggerAPI#48]
Hi Willem,

Are the pre-compiled .bin-files for v3.0.1 also suitable for the ESP-01 board (with 1MB flash)?

If not, could you create them?

Thanks!

**Comment by mrWheel** [comment]
It is not and no, I cannot.
If you upgrade your ESP-01 with 4MB flash you can use the binaries for the "General ESP8266".
