### ISSUE TITLE
Be able to disable wifi hotspot when connected to other wifi network

### ISSUE THREAD

**Issue by PeyPatrick** [mrWheel/DSMRloggerAPI#49]
Using the 4.5 kit with software version 3.0.1 currently. While the DSMR is connected to my main wifi network, it is still broadcasting its own DSMR network. Is there an option to disable this in case the wlan client is connected to an AP?

**Comment by mrWheel** [comment]
It does not if you have a normal connection via your WiFi network.
ESP8266 only has one transmitter for WiFi. It probably is some lag in your network that makes it LOOK like the AP is still there .. but it is not.

**Comment by mrWheel** [comment]
@PeyPatrick 
Versie 3.0.3 zou dit niet meer moeten doen!
Als je tijd hebt om deze versie te testen dan hoor ik graag wat je bevinding(en) is/zijn.
