### ISSUE TITLE
Adding to the new home assistant energy dashboard.

### ISSUE THREAD

**Issue by SJoWie80** [mrWheel/DSMRloggerAPI#50]
Hello,

What do i have to change/add to my config files so that i can Configure grid consumption in the new home assistant energy dashboard?

Regards,
Joey

**Comment by vnijhuis** [comment]
You can do the same for all missing states in the energy config screen as described in the following ticket.

[Issue for adding support to solar edge modbus](https://github.com/binsentsu/home-assistant-solaredge-modbus/issues/22)

**Comment by SamJongenelen** [comment]
Well, I've got energy working for a few weeks, no issues.

I cannot seem to get gas working, and since the update HA energy config tells me the state_class is unexpected

**Comment by vnijhuis** [comment]
It is also configured in a similar fashion.

In customize.yml

```yaml
sensor.gas_delivered:
  device_class: gas
  state_class: total_increasing
```

It can also go into the file where you define your sensor because we create it from MQTT.


Remark on my first comment: 

The config for energy sensors now have last_reset. That can go and all need to have state_class: total_increasing.

![SmartSelect_20210905-065102_Home Assistant.jpg](https://user-images.githubusercontent.com/11654525/132115660-0743b408-744d-4b77-bf31-e5ae7c794fd0.jpg)

**Comment by thomasvt1** [comment]
If you're looking to add the data to home assistant and move to the esphome platform I've just finished writing my working yaml for it;

https://gist.github.com/thomasvt1/6b7167295730a40df6f3eee9a4c275d5

**Comment by NightFalcon650** [comment]
I can't seem to get it to work with the energy dashboard.

Can someone share there configuration.yaml or make a step-by-step tutorial?
Also that the energy dashboard sees al the sensors it needs for it to be aqurate? 
Different tarrifs but also consumed, delivered to the net and generated and used of the solar panels.

Maybe a good update idea for the tutorial..

**Comment by NightFalcon650** [comment]
> Well, I've got energy working for a few weeks, no issues.
> 
> I cannot seem to get gas working, and since the update HA energy config tells me the state_class is unexpected

Could you paste your configuration here?
I'm trying to get it working but not that much luck till now?

**Comment by SamJongenelen** [comment]
I got it working, using m³ as the unit and using an utility meter. I had m3 as unit before
