### ISSUE TITLE
2 kleine UI settings bugs

### ISSUE THREAD

**Issue by gvdhoven** [mrWheel/DSMRloggerAPI#51]
1) Het haakje sluiten symbool van "OLED type" staat na de input box ipv ervoor zoals het bij de rest is.

2) De UI box van de "Oled Screen Time (Min., 0=infinite)" heeft een up en down arrow in de input box maar als je deze gebruikt om van "0" naar een hogere waarde te gaan kun je hem niet meer met die arrows op 0 zetten. Lijkt erop dat de minvalue van de controls op '1' staat.

**Comment by mrWheel** [comment]
Is dit nog steeds zo?
