### ISSUE TITLE
Option to always start AP

### ISSUE THREAD

**Issue by Nuklon** [mrWheel/DSMRloggerAPI#55]
The ESP can run AP mode and connect to another network simultaneously. This is a useful scenario when you don't have your main Wi-Fi enabled 24/7, and log the telegrams externally in DSMR reader (which can connect to the ESP). Perhaps one additional option can be added in the configuration options to enable this behavior (with a password).

**Comment by PCR-2020** [comment]
Weirdly enough I actually have this behavior at the moment (check the IPs). Which is actually scary in my case, since it pokes a large gap in my network security.

**Comment by PCR-2020** [comment]
![Screenshot_20220224-233255_Edge](https://user-images.githubusercontent.com/74598939/155619323-a8e8f589-6ef8-4c0b-bbd4-b03c6a907b02.jpg)

**Comment by mrWheel** [comment]
I know.
No solution yet..

see [here](https://willem.aandewiel.nl/index.php/2020/02/28/restapis-zijn-hip-nieuwe-firmware-voor-de-dsmr-logger/#comment-3965).

**Comment by Nuklon** [comment]
Which version is this fixed in @mrWheel?
