### ISSUE TITLE
Gas consumption not available in HomeAssistant Energy board

### ISSUE THREAD

**Issue by marektyc83** [mrWheel/DSMRloggerAPI#56]
How do i get the correct entity in my Energy dashboard of Homeassistant. 

In my configuration i have added :

  - platform: rest
    name: "DSMR_API_Gas gebruik"
    resource: http://192.168.2.98/api/v1/sm/fields/mbus2_delivered
    unit_of_measurement: m3
    value_template: '{{ (value_json.fields[1].value) | round(3) }}'
    device_class: gas
    state_class: total_increasing

**Comment by mrWheel** [comment]
This is a question better suited as a comment on my website.
