### ISSUE TITLE
Request for information: smart meters that duplicate telegram output every second

### ISSUE THREAD

**Issue by ProBackup-nl** [mrWheel/DSMRloggerAPI#58]
In the blog comments I read that some smart meters output duplicate data every second, at least update their output slower then 1Hz.

Is there more information available?
F.e. 

- Which smart meters suffer from this duplication behavior?
- Will even the time stamp be identical to previous telegrams?
- Which values are identical, and which values change between telegrams?

**Comment by mrWheel** [comment]
I have received reports for SM’s that sends a telegram every second but only updates the data every ten seconds.

not sure which SM’s.
