### ISSUE TITLE
Documentation lacks hardware dimensions

### ISSUE THREAD

**Issue by ProBackup-nl** [mrWheel/DSMRloggerAPI#59]
Documentation at <https://mrwheel.github.io/DSMRloggerWS/hardware_V4.5/#dsmr-logger-versie-45> is linked from opencircuit.nl

Neither <https://opencircuit.nl/product/slimme-meter-uitlezer-v4.5-geassembleerd> nor the documentation at github.io lists the dimensions (length, width, height) of the (1) bare and (2) populated PCB.

PS This info helps to purchase a box that fits the board.

**Comment by ProBackup-nl** [comment]
51×68×16 mm¹

**Comment by mrWheel** [comment]
Thanks @ProBackup-nl
