### ISSUE TITLE
Verzend MQTT Berichten (Sec.) met regelmaat naar 0

### ISSUE THREAD

**Issue by leandresz** [mrWheel/DSMRloggerAPI#63]
Ik heb op externe locatie een DSMR logger met de DSMR-API v3.0.2 draaien. Deze verzend de MQTT berichten elke X periode naar een broker bij mij thuis. Met enige regelmaat veranderd het veld "Verzend MQTT Berichten (Sec.)" naar "0" waardoor ik geen MQTT berichten meer binnen krijg.

Of ik deze waarde nu op 5, 20 of 60 zet. Dat maakt niet uit. Wanneer ik constateer dat HomeAssistant geen updates meer krijgt en ik extern inlog op de DSMR logger dan zie ik dat "Verzend MQTT Berichten (Sec.)" weer eens op "0" staat. Zodra ik dit aanpas naar een getal boven 0 dan komende updates weer binnen.

Is dit een bug?

**Comment by mrWheel** [comment]
Lijkt me een bug.

**Comment by mrWheel** [comment]
Ik kan het niet reproduceren.

**Comment by leandresz** [comment]
Ik vermoed dat dit probleem ontstaat als (kortstondig) de verbinding naar de MQTT broker niet mogelijk is. Als workaround kan ik een queuing broker op locatie neerzetten. Echter mogelijk kan DSMR logger zelf ook (tijdelijk) stoppen met MQTT berichten verzenden wanneer de broker niet bereikbaar is, zonder in de config de "Verzend MQTT Berichten (Sec.)" op 0 te zetten.

**Comment by mrWheel** [comment]
@leandresz ,

Punt blijft dat de software zelf nooit de settingsMQTTinterval op “0” zet!
Dat doet’ie alleen als in de settings geen geldig IPaddress is ingesteld….

Daarnaast stopt de software een bepaalde tijd met verzenden om de draad na enige tijd weer op te pakken.

Als je er achter komt waar en in welke situatie het fout gaat dan kan ik meer uitzoeken!

10-11-2022 - update
Ok, ik lees mijn eigen code niet goed!

ik zal straks een voorstel doen met het verzoek of je dat wilt testen

**Comment by mrWheel** [comment]
@leandresz 

Wil je deze regel weg-be-commentariëren (dit ervoor zetten '`//`'):

https://github.com/mrWheel/DSMRloggerAPI/blob/c04b36dc85cadd39377e401b12c04c822096b41f/MQTTstuff.ino#L86

Hierdoor zal, als er geen verbinding kan worden gemaakt met de MQTT broker, na 5 minuten weer geprobeerd worden contact te maken.

**Comment by leandresz** [comment]
Klinkt idd als een oplossing. Ik ga dat testen!

**Comment by leandresz** [comment]
Compilen gaat nog niet van harte. Maar ik ben er dan ook niet bedreven in.

[image: image.png]
--
Met vriendelijke groet,

Alexander Mulder


Op do 10 nov. 2022 om 10:22 schreef mrWheel ***@***.***>:
