### ISSUE TITLE
geen telegram meer na upgrade 2.0.1 -> 3.0.3

### ISSUE THREAD

**Issue by digiater** [mrWheel/DSMRloggerAPI#65]
na upgrade naar 3.0.3 krijg ik geen telegram meer:

/CTA5ZIV-METER

1-3:0.2.8(50)
0-0:1.0.0(221014124503S)
0-0:96.1.1(4530303639303030373036303438353230)
1-0:1.8.1(015656.494*kWh)
1-0:1.8.2(007273.675*kWh)
1-0:2.8.1(005398.994*kWh)
1-0:2.8.2(011377.465*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.913*kW)
1-0:2.7.0(00.388*kW)
0-0:96.7.21(00052)
0-0:96.7.9(00123)
1-0:99.97.0(10)(0-0:96.7.19)(220926071459S)(0009424614*s)(220926071459S)(0009424614*s)(220926071459S)(0009424614*s)(220901104303S)(0007277098*s)(220901104303S)(0007277098*s)(220901104302S)(0007277097*s)(220807141135S)(0005129610*s)(220807141135S)(0005129610*s)(220807141135S)(0005129610*s)(220713174005S)(0002982120*s)
1-0:32.32.0(00010)
1-0:52.32.0(00013)
1-0:72.32.0(00013)
1-0:32.36.0(00016)
1-0:52.36.0(00038)
1-0:72.36.0(00028)
0-0:96.13.0()
1-0:32.7.0(238.0*V)
1-0:52.7.0(238.0*V)
1-0:72.7.0(239.0*V)
1-0:31.7.0(003*A)
1-0:51.7.0(002*A)
1-0:71.7.0(001*A)
1-0:21.7.0(00.358*kW)
1-0:41.7.0(00.554*kW)
1-0:61.7.0(00.000*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.388*kW)
!6583
Telegram has 1036 chars

[12:44:55][  17440|  5616] processAPI  (  64): from[192.168.13.14] URI[/api/v1/dev/time] method[GET]
[12:44:57][  17688|  5616] processSlimm(  36): handleSlimmerMeter RawCount=[  20]
[12:44:57][  17440|  5616] processAPI  (  64): from[192.168.13.14] URI[/api/v1/sm/actual] method[GET]
[12:44:59][  17440|  5616] processAPI  (  64): from[192.168.13.42] URI[/api/v1/sm/telegram] method[GET]
[12:45:00][  17400|  5616] handleSmV1Ap( 306): read [1014] bytes
[12:45:00][  16056|  5616] handleSmV1Ap( 309): telegram > [1024] bytes. Bailout!

De telegrams lijken te groot en zijn niet meer op te vragen omdat MAX_TLGRM_LENGTH op 1024 staat.

Jur.

**Comment by mrWheel** [comment]
Hm..
Komt door deze `1-0:99.97.0(10)(0-0:96.7.19)` Die kan volgens de specs alleen al 1024 bytes groot worden...

Hoewel:
`[12:45:00][ 17400| 5616] handleSmV1Ap( 306): read [1014] bytes`
.. hij er schijnbaar slecht 1014 heeft geparsed...

Je kunt zelf de maximale grootte aanpassen in `DSMRloggerAPI.h`. Ik zou het dan wat ruim nemen (1200) of zo.

Als je dit hebt aangepast, wil je dan doorgeven wat je hebt gedaan en hoe dit uitpakt?

**Comment by digiater** [comment]
Ik zou het wel willen aanpassen maar dan moet ik eerst een build 
omgeving opbouwen, wat nogal wat tijd gaat kosten (die ik nu niet echt heb).

Ik probeer een downgrade naar 2.0.1 te doen maar krijg dan dit:

Update error: ERROR[10]: Magic byte is wrong, not 0xE9

Hoe kan ik downgraden?

Jur.

**Comment by mrWheel** [comment]
Hi Jur,

Aangepast in[ v3.0.4](https://github.com/mrWheel/DSMRloggerAPI/releases/tag/v3.0.4)
