### ISSUE TITLE
Raw telegram messages via telnet for Home-Assistant

### ISSUE THREAD

**Issue by danito** [mrWheel/DSMRloggerAPI#66]
Hi,

I just got my Slimme meter uitlezer V4.5 with DSMRloggerApi and I'm very glad how it works.
I'm using Home-Assistant and I have first tried to use the [DSMR Slimme lezer integration](https://www.home-assistant.io/integrations/dsmr/) for Home-Assistant via network.
This integration connects to the reader via telnet and expects only raw telegram lines; DSMRloggerApi is a bit too chatty and HA can't cope with all the logs.
Of course I can (and did) use the rest sensors with the provided API, but as HA is already ready for this, would it be difficult to adapt DSMRLoggerApi with the possibility to just get the telegram messages and nothing else over telnet? 
Maybe add a setting that limits the telnet logs output to the raw telegram messages and so HA can read them and no need to use the rest sensor.

Thanks

Daniel

**Comment by mrWheel** [comment]
I'd rather have comments on the post at my website.

If you connect to the DSMR-logger by `telnet` and enter a `"p"` you will get 19 (raw) telegrams at the interval you set in the settings.

After 19 telegrams you have to enter a `"p"` again.

If it is "to chatty" for your application, you can remove the extra debug messages and, for your use case maybe, the test of `RawCount` to stop the DSMR-logger from stop sending the raw telegram data to `telnet`. 
But be aware that while sending raw telegram output to `telnet` the _web-interface_ and probably the _restAPI_'s won't work as smooth as you may want.
