### ISSUE TITLE
Add support for Fluvius V1.7.1 DSMR messages

### ISSUE THREAD

**Issue by debouttek** [mrWheel/DSMRloggerAPI#68]
Hi
Is it possible to update for Belgium?
From 01/01/2023 there is a quarterly measurement of peak tariff.

I found some info on GitHub. 
https://maakjemeterslim.be/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0lEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cdd9b48fd0838e89b177f03b745b23450fd8f53e/e-MUCS_P1_Ed_1_7_1.pdf?disposition=attachment

https://github.com/ndokter/dsmr_parser/commit/d05fe2692bce9da5bca4103008a6327b4901106a

Thanks in advance

**Comment by mrWheel** [comment]
Maybe you should read [this](https://mrwheel-docs.gitbook.io/dsmrlogger32/).
