### ISSUE TITLE
p1meter start niet meer op na MQTT wijziging

### ISSUE THREAD

**Issue by gotiniens** [mrWheel/DSMRloggerAPI#69]
Ik heb gisteren op mijn DSMRlogger V3.0.4 een MQTT broker geconfigureerd. Dat leek niet direct te werken, dus ik heb hem een reboot gegeven vanuit de webinterface.

Hij is helaas hierna niet stabiel terug gekomen. Mijn eerste indicator dat er wat mis is was dit ping resultaat:

> PING DSMRlogger (local_subnet.135) 56(84) bytes of data.
> <KNIP>
> From laptop (local_subnet.121) icmp_seq=751 Destination Host Unreachable
> From laptop (local_subnet.121) icmp_seq=752 Destination Host Unreachable
> From laptop (local_subnet.121) icmp_seq=753 Destination Host Unreachable
> 64 bytes from DSMRlogger (local_subnet.135): icmp_seq=759 ttl=255 time=139 ms
> 64 bytes from DSMRlogger (local_subnet.135): icmp_seq=765 ttl=255 time=270 ms
> 64 bytes from DSMRlogger (local_subnet.135): icmp_seq=775 ttl=255 time=40.0 ms
> 64 bytes from DSMRlogger (local_subnet.135): icmp_seq=776 ttl=255 time=8.36 ms
> From laptop (local_subnet.121) icmp_seq=787 Destination Host Unreachable
> From laptop (local_subnet.121) icmp_seq=788 Destination Host Unreachable
> <KNIP>
> --- DSMRlogger ping statistics ---
> 898 packets transmitted, 66 received, +152 errors, 92.6503% packet loss, time 916576ms
> rtt min/avg/max/mdev = 5.686/194.516/2253.284/307.312 ms, pipe 4
> 

Als ik de DSMRlogger reboot door de P1 kabel eruit te halen, en er weer in te steken zie ik dat hij een tijdje goed reageert op ping berichten, en daarna weer hetzelfde gedrag vertoont.

Als ik zo snel mogelijk verbind met de telnet poort, zie ik dat de DSMRlogger wel opstart, maar het lijkt erop dat hij bij het verwerken van het eerse telegram vast loopt:

> Connected to WIFI
> IP address: local_subnet135
> IP gateway: local_subnet254
> 
> [21:00:03][  25272| 24920] startMDNS   ( 134): [1] mDNS setup as [DSMR-API.local]
> [21:00:03][  23416| 23376] startMDNS   ( 137): [2] mDNS responder started as [DSMR-API.local]
> [21:00:05][  24736| 23256] startNTP    (  44): Starting UDP
> [21:00:05][  23160| 22608] startNTP    (  46): Local port: 8888
> [21:00:05][  23264| 22608] startNTP    (  48): waiting for NTP sync
> Transmit NTP Request
> nl.pool.ntp.org: 158.101.221.122
> Received NTP Response => new time [2023-02-08 21:17:42 (CET)]
> Daylight Saving Time
> NTP time is [2023-02-08 22:17:42 (CEST)]
> Transmit NTP Request
> 0.nl.pool.ntp.org: 129.250.35.251
> Received NTP Response => new time [2023-02-08 21:17:42 (CET)]
> Daylight Saving Time
> NTP time is [2023-02-08 22:17:42 (CEST)]
> [22:17:42][  23152| 22608] setup       ( 341): NTP time is [2023-02-08 22:17:42 (CEST)]
> [22:17:43][  24496| 23256] setup       ( 353): Last reset reason: [External System]
> [22:17:43][  23152| 22608] DSMRfileExis( 650): check if [/DSMRindex.html] exists .. Yes! OK!
> [22:17:44][  24496| 23256] DSMRfileExis( 650): check if [/DSMRindex.html] exists .. Yes! OK!
> [22:17:44][  24496| 23256] DSMRfileExis( 650): check if [/DSMRindex.js] exists .. Yes! OK!
> [22:17:45][  24496| 23256] DSMRfileExis( 650): check if [/DSMRindex.css] exists .. Yes! OK!
> [22:17:45][  24496| 23256] DSMRfileExis( 650): check if [/DSMRgraphics.js] exists .. Yes! OK!
> [22:17:46][  24496| 23256] DSMRfileExis( 650): check if [/FSmanager.html] exists .. Yes! OK!
> [22:17:47][  23992| 23256] DSMRfileExis( 650): check if [/FSmanager.css] exists .. Yes! OK!
> Daylight Saving Time
> [22:17:47][  22624| 21960] setup       ( 417): Time is set to [230208221747S] from NTP
> [22:17:50][  23968| 23256] setup       ( 446): FSYS correct populated -> normal operation!
> [22:17:53][  22456| 22256] setup       ( 492): HTTP server gestart
> [22:17:56][  22456| 22256] processMinde(  93): Mindergas State: MG_INIT
> [22:17:56][  21112| 20960] processMinde( 121): MinderGas Authtoken is not set, no update can be done.
> [22:17:56][  21112| 20960] setup       ( 515): Startup complete! actTimestamp[230208205956W]
> [22:17:56][  21112| 20960] setup       ( 524): Last reset reason: [External System]
> [22:17:56][  22032| 21672] setup       ( 536): Enable slimmeMeter..
> [22:17:56][  20688| 20376] setup       ( 539): Swapping serial port to Smart Meter, debug output will continue on telnet
> [22:17:56][  22032| 21672] setup       ( 543): Serial will be set to 115200 baud / 7N1
> 
> Commands are:
> 
>    B - Board Info
>   *E - erase file from FSYS
>    L - list Settings
>    D - Display Day table from FSYS
>    H - Display Hour table from FSYS
>    M - Display Month table from FSYS
>    I - Identify by blinking LED on GPIO[02]
>    P - No Parsing (show RAW data from Smart Meter)
>   *W - Force Re-Config WiFi
>   *R - Reboot
>    S - File info on FSYS
>   *U - Update FSYS (save Data-files)
>   *Z - Zero counters
> 
>    V - Toggle Verbose 1
>    T - Force update mindergas.nl
> [22:18:07][  20448| 19696] processSlimm(  83): telegramCount=[101611] telegramErrors=[0]
> 
> [Time----][FreeHeap/mBlck][Function----(line):
> [22:18:07][  19488| 19048] modifyMbusDe( 203): mbus1_delivered [2614.036]
> [22:18:07][  19488| 19048] modifyMbusDe( 207): gasDelivered .. [2614.036]
> [22:18:07][  19488| 19048] processTeleg(  15): Telegram[101612]=>DSMRdata.timestamp[230208211840W]
> [21:18:40][  19488| 19048] processTeleg(  44): actHour[20] -- newHour[21]
> [20:59:56][  19488| 19048] writeDataToF( 221): >23020820;  waarde;  waarde;  waarde;  waarde;  2614.036;         ;[21:18:40][  20832| 19696] writeLastSta(  69): writeLastStatus() => 230208205956W; 6; 0; 101612;
> <DIT IS DE LAATSTE REGEL DIE IK ONTVANG>

Door dit alles heb ik het idee dat er iets mis is met mijn MQTT config, en zou deze dus graag ongedaan willen maken. Maar aangezien de webinterface nooit bereikbaar wordt kan ik het niet daar doen, of via de API.

Een factory reset zou kunnen, maar kan nergens in de documentatie vinden hoe dat moet? Wat nu? Misschien is er een andere oplossing om dit toch te fixen?

p.s. Na de installatie van V3.0.4 2 weken geleden had ik ook al wat problemen met opstarten, ik heb het niet echt meer heel helder voor de geest, maar ik denk dat dat voornamelijk was omdat de DSMRLogger geen internet had voor de NTP connectie. Al kan het ook een algemener probleem zijn.

**Comment by mrWheel** [comment]
@gotiniens 
Als de DSMR-logger een slechte verbinding heeft met je WiFi AP dan krijg je lange ping tijden en een onbetrouwbare verbinding.
Deze regel snap ik niet:
`
[20:59:56][ 19488| 19048] writeDataToF( 221): >23020820; waarde; waarde; waarde; waarde; 2614.036; ;[21:18:40][ 20832| 19696] writeLastSta( 69): writeLastStatus() => 230208205956W; 6; 0; 101612;
`

`waarde;waarde;..`?

Dat het probleem aan je MQTT configuratie zou liggen lijkt me onwaarschijnlijk want ik zie geen logging dat de DSMR-logger daar al mee bezig is.

Ik zou, om te beginnen, je modem resetten en kijken of het dan beter wordt.

Dit soort vragen kun je beter via mijn website als een comment stellen. 

Zie bijvoorbeeld de comment’s van Pieter Duin.
