### ISSUE TITLE
3.0.4 release notes zijn qua volgorde niet helemaal duidelijk

### ISSUE THREAD

**Issue by ProBackup-nl** [mrWheel/DSMRloggerAPI#70]
Eerst "DSMRloggerAPI.ino.bin" uploaden,

of eerst de nieuwe bestanden

-     DSMRindex.html
-     DSMRindex.js
-     DSMRversion.dat

naar het bestandssysteem uploaden en daarna "DSMRloggerAPI.ino.bin" flashen?

**Comment by mrWheel** [comment]
Maakt niet uit.
