### ISSUE TITLE
Reset values without uploading everything

### ISSUE THREAD

**Issue by arjenv** [mrWheel/DSMRloggerAPI#75]
I'm sure I read it somewhere, but cannot find it anymore. How can I reset the values I read from the P1meter? i want to start fresh but do not want to start 'all over'.

Just remove all the RING*.csv files?

Thanks

**Comment by mrWheel** [comment]
Yes!
Just remove the RING files (first download them to your computer, just to be sure) then reboot the DSMRlogger
